image: golang:1.12

variables:
  BIN_NAME: GlenGoRestApi
  ARTIFACTS_DIR: artifacts
  GO_PROJECT: gitlab.hal.davecutting.uk/40233306/glengorestapi

stages:
  - build
  - test

before_script:
  - mkdir -p ${GOPATH}/src/${GO_PROJECT}
  - mkdir -p ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}
  - go get -u github.com/Masterminds/glide
  - cp -r ${CI_PROJECT_DIR}/* ${GOPATH}/src/${GO_PROJECT}/
  - cd ${GOPATH}/src/${GO_PROJECT}

build-projectname:
  stage: build
  script:
    - glide install
    - go build -o ${CI_PROJECT_DIR}/${ARTIFACTS_DIR}/${BIN_NAME} cmd/awesome-server/main.go
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}

test-projectname:
  stage: test
  script:
    - glide install
    - go test -v -cover ./...
